version: '3.8'
services:
  domestika-downloader:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - './src:/app/src'
      - './public:/app/public'
      - './package-lock.json:/app/package-lock.json'
      - './package.json:/app/package.json'
